/**
 * Catálogo mundial de países de destino (ISO 3166-1 alfa-2).
 *
 * Global destination countries catalog (ISO 3166-1 alpha-2).
 * Used in checkout for worldwide shipping. Rates resolved in config.ts.
 */

export interface CountryOption {
  code: string;
  name: string;
  flag: string;
}

export const worldCountries: CountryOption[] = [
  { code: 'AF', name: `Afghanistan`, flag: '🇦🇫' },
  { code: 'AL', name: `Albania`, flag: '🇦🇱' },
  { code: 'DE', name: `Germany`, flag: '🇩🇪' },
  { code: 'AD', name: `Andorra`, flag: '🇦🇩' },
  { code: 'AO', name: `Angola`, flag: '🇦🇴' },
  { code: 'AI', name: `Anguilla`, flag: '🇦🇮' },
  { code: 'AG', name: `Antigua and Barbuda`, flag: '🇦🇬' },
  { code: 'SA', name: `Saudi Arabia`, flag: '🇸🇦' },
  { code: 'DZ', name: `Algeria`, flag: '🇩🇿' },
  { code: 'AR', name: `Argentina`, flag: '🇦🇷' },
  { code: 'AM', name: `Armenia`, flag: '🇦🇲' },
  { code: 'AW', name: `Aruba`, flag: '🇦🇼' },
  { code: 'AU', name: `Australia`, flag: '🇦🇺' },
  { code: 'AT', name: `Austria`, flag: '🇦🇹' },
  { code: 'AZ', name: `Azerbaijan`, flag: '🇦🇿' },
  { code: 'BS', name: `Bahamas`, flag: '🇧🇸' },
  { code: 'BD', name: `Bangladesh`, flag: '🇧🇩' },
  { code: 'BB', name: `Barbados`, flag: '🇧🇧' },
  { code: 'BH', name: `Bahrain`, flag: '🇧🇭' },
  { code: 'BE', name: `Belgium`, flag: '🇧🇪' },
  { code: 'BZ', name: `Belize`, flag: '🇧🇿' },
  { code: 'BJ', name: `Benin`, flag: '🇧🇯' },
  { code: 'BM', name: `Bermuda`, flag: '🇧🇲' },
  { code: 'BY', name: `Belarus`, flag: '🇧🇾' },
  { code: 'BO', name: `Bolivia`, flag: '🇧🇴' },
  { code: 'BA', name: `Bosnia and Herzegovina`, flag: '🇧🇦' },
  { code: 'BW', name: `Botswana`, flag: '🇧🇼' },
  { code: 'BR', name: `Brazil`, flag: '🇧🇷' },
  { code: 'BN', name: `Brunei`, flag: '🇧🇳' },
  { code: 'BG', name: `Bulgaria`, flag: '🇧🇬' },
  { code: 'BF', name: `Burkina Faso`, flag: '🇧🇫' },
  { code: 'BI', name: `Burundi`, flag: '🇧🇮' },
  { code: 'BT', name: `Bhutan`, flag: '🇧🇹' },
  { code: 'CV', name: `Cabo Verde`, flag: '🇨🇻' },
  { code: 'KH', name: `Cambodia`, flag: '🇰🇭' },
  { code: 'CM', name: `Cameroon`, flag: '🇨🇲' },
  { code: 'CA', name: `Canada`, flag: '🇨🇦' },
  { code: 'BQ', name: `Caribbean Netherlands`, flag: '🇧🇶' },
  { code: 'QA', name: `Qatar`, flag: '🇶🇦' },
  { code: 'TD', name: `Chad`, flag: '🇹🇩' },
  { code: 'CZ', name: `Czechia`, flag: '🇨🇿' },
  { code: 'CL', name: `Chile`, flag: '🇨🇱' },
  { code: 'CN', name: `China`, flag: '🇨🇳' },
  { code: 'CY', name: `Cyprus`, flag: '🇨🇾' },
  { code: 'VA', name: `Vatican City`, flag: '🇻🇦' },
  { code: 'CO', name: `Colombia`, flag: '🇨🇴' },
  { code: 'KM', name: `Comoros`, flag: '🇰🇲' },
  { code: 'CG', name: `Congo`, flag: '🇨🇬' },
  { code: 'KP', name: `North Korea`, flag: '🇰🇵' },
  { code: 'KR', name: `South Korea`, flag: '🇰🇷' },
  { code: 'CR', name: `Costa Rica`, flag: '🇨🇷' },
  { code: 'CI', name: `Ivory Coast`, flag: '🇨🇮' },
  { code: 'HR', name: `Croatia`, flag: '🇭🇷' },
  { code: 'CU', name: `Cuba`, flag: '🇨🇺' },
  { code: 'CW', name: `Curaçao`, flag: '🇨🇼' },
  { code: 'DK', name: `Denmark`, flag: '🇩🇰' },
  { code: 'DM', name: `Dominica`, flag: '🇩🇲' },
  { code: 'EC', name: `Ecuador`, flag: '🇪🇨' },
  { code: 'EG', name: `Egypt`, flag: '🇪🇬' },
  { code: 'SV', name: `El Salvador`, flag: '🇸🇻' },
  { code: 'AE', name: `United Arab Emirates`, flag: '🇦🇪' },
  { code: 'ER', name: `Eritrea`, flag: '🇪🇷' },
  { code: 'SK', name: `Slovakia`, flag: '🇸🇰' },
  { code: 'SI', name: `Slovenia`, flag: '🇸🇮' },
  { code: 'ES', name: `Spain`, flag: '🇪🇸' },
  { code: 'US', name: `United States`, flag: '🇺🇸' },
  { code: 'EE', name: `Estonia`, flag: '🇪🇪' },
  { code: 'SZ', name: `Eswatini`, flag: '🇸🇿' },
  { code: 'ET', name: `Ethiopia`, flag: '🇪🇹' },
  { code: 'PH', name: `Philippines`, flag: '🇵🇭' },
  { code: 'FI', name: `Finlandia`, flag: '🇫🇮' },
  { code: 'FJ', name: `Fiji`, flag: '🇫🇯' },
  { code: 'FR', name: `France`, flag: '🇫🇷' },
  { code: 'GA', name: `Gabon`, flag: '🇬🇦' },
  { code: 'GM', name: `Gambia`, flag: '🇬🇲' },
  { code: 'GE', name: `Georgia`, flag: '🇬🇪' },
  { code: 'GH', name: `Ghana`, flag: '🇬🇭' },
  { code: 'GI', name: `Gibraltar`, flag: '🇬🇮' },
  { code: 'GD', name: `Grenada`, flag: '🇬🇩' },
  { code: 'GR', name: `Greece`, flag: '🇬🇷' },
  { code: 'GL', name: `Greenland`, flag: '🇬🇱' },
  { code: 'GP', name: `Guadeloupe`, flag: '🇬🇵' },
  { code: 'GU', name: `Guam`, flag: '🇬🇺' },
  { code: 'GT', name: `Guatemala`, flag: '🇬🇹' },
  { code: 'GF', name: `French Guiana`, flag: '🇬🇫' },
  { code: 'GG', name: `Guernsey`, flag: '🇬🇬' },
  { code: 'GN', name: `Guinea`, flag: '🇬🇳' },
  { code: 'GQ', name: `Equatorial Guinea`, flag: '🇬🇶' },
  { code: 'GW', name: `Guinea-Bissau`, flag: '🇬🇼' },
  { code: 'GY', name: `Guyana`, flag: '🇬🇾' },
  { code: 'HT', name: `Haiti`, flag: '🇭🇹' },
  { code: 'HN', name: `Honduras`, flag: '🇭🇳' },
  { code: 'HU', name: `Hungary`, flag: '🇭🇺' },
  { code: 'IN', name: `India`, flag: '🇮🇳' },
  { code: 'ID', name: `Indonesia`, flag: '🇮🇩' },
  { code: 'IQ', name: `Iraq`, flag: '🇮🇶' },
  { code: 'IR', name: `Iran`, flag: '🇮🇷' },
  { code: 'IE', name: `Ireland`, flag: '🇮🇪' },
  { code: 'IM', name: `Isle of Man`, flag: '🇮🇲' },
  { code: 'CX', name: `Christmas Island`, flag: '🇨🇽' },
  { code: 'NF', name: `Norfolk Island`, flag: '🇳🇫' },
  { code: 'IS', name: `Iceland`, flag: '🇮🇸' },
  { code: 'KY', name: `Cayman Islands`, flag: '🇰🇾' },
  { code: 'CC', name: `Cocos Islands`, flag: '🇨🇨' },
  { code: 'CK', name: `Cook Islands`, flag: '🇨🇰' },
  { code: 'FO', name: `Faroe Islands`, flag: '🇫🇴' },
  { code: 'FK', name: `Falkland Islands`, flag: '🇫🇰' },
  { code: 'MP', name: `Northern Mariana Islands`, flag: '🇲🇵' },
  { code: 'MH', name: `Marshall Islands`, flag: '🇲🇭' },
  { code: 'SB', name: `Solomon Islands`, flag: '🇸🇧' },
  { code: 'TC', name: `Turks and Caicos Islands`, flag: '🇹🇨' },
  { code: 'VG', name: `British Virgin Islands`, flag: '🇻🇬' },
  { code: 'VI', name: `US Virgin Islands`, flag: '🇻🇮' },
  { code: 'IL', name: `Israel`, flag: '🇮🇱' },
  { code: 'IT', name: `Italy`, flag: '🇮🇹' },
  { code: 'JM', name: `Jamaica`, flag: '🇯🇲' },
  { code: 'JP', name: `Japan`, flag: '🇯🇵' },
  { code: 'JE', name: `Jersey`, flag: '🇯🇪' },
  { code: 'JO', name: `Jordan`, flag: '🇯🇴' },
  { code: 'KZ', name: `Kazakhstan`, flag: '🇰🇿' },
  { code: 'KE', name: `Kenya`, flag: '🇰🇪' },
  { code: 'KG', name: `Kyrgyzstan`, flag: '🇰🇬' },
  { code: 'KI', name: `Kiribati`, flag: '🇰🇮' },
  { code: 'XK', name: `Kosovo`, flag: '🇽🇰' },
  { code: 'KW', name: `Kuwait`, flag: '🇰🇼' },
  { code: 'LA', name: `Laos`, flag: '🇱🇦' },
  { code: 'LS', name: `Lesotho`, flag: '🇱🇸' },
  { code: 'LV', name: `Latvia`, flag: '🇱🇻' },
  { code: 'LB', name: `Lebanon`, flag: '🇱🇧' },
  { code: 'LR', name: `Liberia`, flag: '🇱🇷' },
  { code: 'LY', name: `Libya`, flag: '🇱🇾' },
  { code: 'LI', name: `Liechtenstein`, flag: '🇱🇮' },
  { code: 'LT', name: `Lithuania`, flag: '🇱🇹' },
  { code: 'LU', name: `Luxembourg`, flag: '🇱🇺' },
  { code: 'MK', name: `North Macedonia`, flag: '🇲🇰' },
  { code: 'MG', name: `Madagascar`, flag: '🇲🇬' },
  { code: 'MY', name: `Malaysia`, flag: '🇲🇾' },
  { code: 'MW', name: `Malawi`, flag: '🇲🇼' },
  { code: 'MV', name: `Maldives`, flag: '🇲🇻' },
  { code: 'ML', name: `Mali`, flag: '🇲🇱' },
  { code: 'MT', name: `Malta`, flag: '🇲🇹' },
  { code: 'MA', name: `Morocco`, flag: '🇲🇦' },
  { code: 'MQ', name: `Martinique`, flag: '🇲🇶' },
  { code: 'MU', name: `Mauritius`, flag: '🇲🇺' },
  { code: 'MR', name: `Mauritania`, flag: '🇲🇷' },
  { code: 'YT', name: `Mayotte`, flag: '🇾🇹' },
  { code: 'MX', name: `Mexico`, flag: '🇲🇽' },
  { code: 'FM', name: `Micronesia`, flag: '🇫🇲' },
  { code: 'MD', name: `Moldavia`, flag: '🇲🇩' },
  { code: 'MC', name: `Monaco`, flag: '🇲🇨' },
  { code: 'MN', name: `Mongolia`, flag: '🇲🇳' },
  { code: 'ME', name: `Montenegro`, flag: '🇲🇪' },
  { code: 'MS', name: `Montserrat`, flag: '🇲🇸' },
  { code: 'MZ', name: `Mozambique`, flag: '🇲🇿' },
  { code: 'MM', name: `Myanmar`, flag: '🇲🇲' },
  { code: 'NA', name: `Namibia`, flag: '🇳🇦' },
  { code: 'NR', name: `Nauru`, flag: '🇳🇷' },
  { code: 'NP', name: `Nepal`, flag: '🇳🇵' },
  { code: 'NI', name: `Nicaragua`, flag: '🇳🇮' },
  { code: 'NE', name: `Niger`, flag: '🇳🇪' },
  { code: 'NG', name: `Nigeria`, flag: '🇳🇬' },
  { code: 'NU', name: `Niue`, flag: '🇳🇺' },
  { code: 'NO', name: `Norway`, flag: '🇳🇴' },
  { code: 'NC', name: `New Caledonia`, flag: '🇳🇨' },
  { code: 'NZ', name: `New Zealand`, flag: '🇳🇿' },
  { code: 'OM', name: `Oman`, flag: '🇴🇲' },
  { code: 'NL', name: `Netherlands`, flag: '🇳🇱' },
  { code: 'PK', name: `Pakistan`, flag: '🇵🇰' },
  { code: 'PW', name: `Palau`, flag: '🇵🇼' },
  { code: 'PA', name: `Panama`, flag: '🇵🇦' },
  { code: 'PG', name: `Papua New Guinea`, flag: '🇵🇬' },
  { code: 'PY', name: `Paraguay`, flag: '🇵🇾' },
  { code: 'PE', name: `Peru`, flag: '🇵🇪' },
  { code: 'PF', name: `French Polynesia`, flag: '🇵🇫' },
  { code: 'PL', name: `Poland`, flag: '🇵🇱' },
  { code: 'PT', name: `Portugal`, flag: '🇵🇹' },
  { code: 'PR', name: `Puerto Rico`, flag: '🇵🇷' },
  { code: 'HK', name: `Hong Kong`, flag: '🇭🇰' },
  { code: 'MO', name: `Macao`, flag: '🇲🇴' },
  { code: 'GB', name: `United Kingdom`, flag: '🇬🇧' },
  { code: 'CF', name: `Central African Republic`, flag: '🇨🇫' },
  { code: 'CD', name: `DR Congo`, flag: '🇨🇩' },
  { code: 'DO', name: `Dominican Republic`, flag: '🇩🇴' },
  { code: 'RE', name: `Réunion`, flag: '🇷🇪' },
  { code: 'RW', name: `Rwanda`, flag: '🇷🇼' },
  { code: 'RO', name: `Romania`, flag: '🇷🇴' },
  { code: 'RU', name: `Russia`, flag: '🇷🇺' },
  { code: 'EH', name: `Western Sahara`, flag: '🇪🇭' },
  { code: 'WS', name: `Samoa`, flag: '🇼🇸' },
  { code: 'AS', name: `American Samoa`, flag: '🇦🇸' },
  { code: 'BL', name: `Saint Barthélemy`, flag: '🇧🇱' },
  { code: 'KN', name: `Saint Kitts and Nevis`, flag: '🇰🇳' },
  { code: 'SM', name: `San Marino`, flag: '🇸🇲' },
  { code: 'MF', name: `Saint Martin`, flag: '🇲🇫' },
  { code: 'PM', name: `Saint Pierre and Miquelon`, flag: '🇵🇲' },
  { code: 'VC', name: `Saint Vincent and the Grenadines`, flag: '🇻🇨' },
  { code: 'SH', name: `Saint Helena`, flag: '🇸🇭' },
  { code: 'LC', name: `Saint Lucia`, flag: '🇱🇨' },
  { code: 'ST', name: `São Tomé and Príncipe`, flag: '🇸🇹' },
  { code: 'SN', name: `Senegal`, flag: '🇸🇳' },
  { code: 'RS', name: `Serbia`, flag: '🇷🇸' },
  { code: 'SC', name: `Seychelles`, flag: '🇸🇨' },
  { code: 'SL', name: `Sierra Leone`, flag: '🇸🇱' },
  { code: 'SG', name: `Singapore`, flag: '🇸🇬' },
  { code: 'SX', name: `Sint Maarten`, flag: '🇸🇽' },
  { code: 'SY', name: `Syria`, flag: '🇸🇾' },
  { code: 'SO', name: `Somalia`, flag: '🇸🇴' },
  { code: 'LK', name: `Sri Lanka`, flag: '🇱🇰' },
  { code: 'ZA', name: `South Africa`, flag: '🇿🇦' },
  { code: 'SD', name: `Sudan`, flag: '🇸🇩' },
  { code: 'SS', name: `South Sudan`, flag: '🇸🇸' },
  { code: 'SE', name: `Sweden`, flag: '🇸🇪' },
  { code: 'CH', name: `Switzerland`, flag: '🇨🇭' },
  { code: 'SR', name: `Suriname`, flag: '🇸🇷' },
  { code: 'TH', name: `Thailand`, flag: '🇹🇭' },
  { code: 'TW', name: `Taiwan`, flag: '🇹🇼' },
  { code: 'TZ', name: `Tanzania`, flag: '🇹🇿' },
  { code: 'TJ', name: `Tajikistan`, flag: '🇹🇯' },
  { code: 'IO', name: `British Indian Ocean Territory`, flag: '🇮🇴' },
  { code: 'PS', name: `Palestine`, flag: '🇵🇸' },
  { code: 'TL', name: `Timor-Leste`, flag: '🇹🇱' },
  { code: 'TG', name: `Togo`, flag: '🇹🇬' },
  { code: 'TK', name: `Tokelau`, flag: '🇹🇰' },
  { code: 'TO', name: `Tonga`, flag: '🇹🇴' },
  { code: 'TT', name: `Trinidad and Tobago`, flag: '🇹🇹' },
  { code: 'TN', name: `Tunisia`, flag: '🇹🇳' },
  { code: 'TM', name: `Turkmenistan`, flag: '🇹🇲' },
  { code: 'TR', name: `Turkey`, flag: '🇹🇷' },
  { code: 'TV', name: `Tuvalu`, flag: '🇹🇻' },
  { code: 'UA', name: `Ukraine`, flag: '🇺🇦' },
  { code: 'UG', name: `Uganda`, flag: '🇺🇬' },
  { code: 'UY', name: `Uruguay`, flag: '🇺🇾' },
  { code: 'UZ', name: `Uzbekistan`, flag: '🇺🇿' },
  { code: 'VU', name: `Vanuatu`, flag: '🇻🇺' },
  { code: 'VE', name: `Venezuela`, flag: '🇻🇪' },
  { code: 'VN', name: `Vietnam`, flag: '🇻🇳' },
  { code: 'WF', name: `Wallis and Futuna`, flag: '🇼🇫' },
  { code: 'YE', name: `Yemen`, flag: '🇾🇪' },
  { code: 'DJ', name: `Djibouti`, flag: '🇩🇯' },
  { code: 'ZM', name: `Zambia`, flag: '🇿🇲' },
  { code: 'ZW', name: `Zimbabwe`, flag: '🇿🇼' },
];

const byCode = new Map(worldCountries.map((c) => [c.code, c]));

/** Devuelve el país por código ISO, o undefined si no existe. */
export function findCountry(code: string): CountryOption | undefined {
  return byCode.get(String(code ?? '').toUpperCase().slice(0, 2));
}

/** true si el código es un país ISO 3166-1 válido y soportado. */
export function isSupportedCountry(code: string): boolean {
  return byCode.has(String(code ?? '').toUpperCase().slice(0, 2));
}
