/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SeguimientoRouteImport } from './routes/seguimiento'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OrigenesRouteImport } from './routes/origenes'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ProductosSkuRouteImport } from './routes/productos.$sku'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiPublicSupSyncTrackingRouteImport } from './routes/api/public/sup/sync-tracking'
import { Route as ApiPublicSupSyncCatalogRouteImport } from './routes/api/public/sup/sync-catalog'
import { Route as ApiPublicSupShippingRouteImport } from './routes/api/public/sup/shipping'
import { Route as ApiPublicAuditConnectionsRouteImport } from './routes/api/public/audit/connections'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SeguimientoRoute = SeguimientoRouteImport.update({
  id: '/seguimiento',
  path: '/seguimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrigenesRoute = OrigenesRouteImport.update({
  id: '/origenes',
  path: '/origenes',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosSkuRoute = ProductosSkuRouteImport.update({
  id: '/productos/$sku',
  path: '/productos/$sku',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const ApiPublicSupSyncTrackingRoute =
  ApiPublicSupSyncTrackingRouteImport.update({
    id: '/api/public/sup/sync-tracking',
    path: '/api/public/sup/sync-tracking',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSupSyncCatalogRoute = ApiPublicSupSyncCatalogRouteImport.update({
  id: '/api/public/sup/sync-catalog',
  path: '/api/public/sup/sync-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSupShippingRoute = ApiPublicSupShippingRouteImport.update({
  id: '/api/public/sup/shipping',
  path: '/api/public/sup/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuditConnectionsRoute =
  ApiPublicAuditConnectionsRouteImport.update({
    id: '/api/public/audit/connections',
    path: '/api/public/audit/connections',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/origenes': typeof OrigenesRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/seguimiento': typeof SeguimientoRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/productos/$sku': typeof ProductosSkuRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/api/public/audit/connections': typeof ApiPublicAuditConnectionsRoute
  '/api/public/sup/shipping': typeof ApiPublicSupShippingRoute
  '/api/public/sup/sync-catalog': typeof ApiPublicSupSyncCatalogRoute
  '/api/public/sup/sync-tracking': typeof ApiPublicSupSyncTrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/origenes': typeof OrigenesRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/seguimiento': typeof SeguimientoRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/productos/$sku': typeof ProductosSkuRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products': typeof ProductsIndexRoute
  '/api/public/audit/connections': typeof ApiPublicAuditConnectionsRoute
  '/api/public/sup/shipping': typeof ApiPublicSupShippingRoute
  '/api/public/sup/sync-catalog': typeof ApiPublicSupSyncCatalogRoute
  '/api/public/sup/sync-tracking': typeof ApiPublicSupSyncTrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/origenes': typeof OrigenesRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/seguimiento': typeof SeguimientoRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/productos/$sku': typeof ProductosSkuRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/api/public/audit/connections': typeof ApiPublicAuditConnectionsRoute
  '/api/public/sup/shipping': typeof ApiPublicSupShippingRoute
  '/api/public/sup/sync-catalog': typeof ApiPublicSupSyncCatalogRoute
  '/api/public/sup/sync-tracking': typeof ApiPublicSupSyncTrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/disclaimer'
    | '/origenes'
    | '/privacy'
    | '/search'
    | '/seguimiento'
    | '/shipping'
    | '/sitemap.xml'
    | '/terms'
    | '/checkout/return'
    | '/collections/$slug'
    | '/productos/$sku'
    | '/products/$slug'
    | '/products/'
    | '/api/public/audit/connections'
    | '/api/public/sup/shipping'
    | '/api/public/sup/sync-catalog'
    | '/api/public/sup/sync-tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/disclaimer'
    | '/origenes'
    | '/privacy'
    | '/search'
    | '/seguimiento'
    | '/shipping'
    | '/sitemap.xml'
    | '/terms'
    | '/checkout/return'
    | '/collections/$slug'
    | '/productos/$sku'
    | '/products/$slug'
    | '/products'
    | '/api/public/audit/connections'
    | '/api/public/sup/shipping'
    | '/api/public/sup/sync-catalog'
    | '/api/public/sup/sync-tracking'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/disclaimer'
    | '/origenes'
    | '/privacy'
    | '/search'
    | '/seguimiento'
    | '/shipping'
    | '/sitemap.xml'
    | '/terms'
    | '/checkout/return'
    | '/collections/$slug'
    | '/productos/$sku'
    | '/products/$slug'
    | '/products/'
    | '/api/public/audit/connections'
    | '/api/public/sup/shipping'
    | '/api/public/sup/sync-catalog'
    | '/api/public/sup/sync-tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  OrigenesRoute: typeof OrigenesRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SeguimientoRoute: typeof SeguimientoRoute
  ShippingRoute: typeof ShippingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  ProductosSkuRoute: typeof ProductosSkuRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiPublicAuditConnectionsRoute: typeof ApiPublicAuditConnectionsRoute
  ApiPublicSupShippingRoute: typeof ApiPublicSupShippingRoute
  ApiPublicSupSyncCatalogRoute: typeof ApiPublicSupSyncCatalogRoute
  ApiPublicSupSyncTrackingRoute: typeof ApiPublicSupSyncTrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguimiento': {
      id: '/seguimiento'
      path: '/seguimiento'
      fullPath: '/seguimiento'
      preLoaderRoute: typeof SeguimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/origenes': {
      id: '/origenes'
      path: '/origenes'
      fullPath: '/origenes'
      preLoaderRoute: typeof OrigenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$sku': {
      id: '/productos/$sku'
      path: '/productos/$sku'
      fullPath: '/productos/$sku'
      preLoaderRoute: typeof ProductosSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/api/public/sup/sync-tracking': {
      id: '/api/public/sup/sync-tracking'
      path: '/api/public/sup/sync-tracking'
      fullPath: '/api/public/sup/sync-tracking'
      preLoaderRoute: typeof ApiPublicSupSyncTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sup/sync-catalog': {
      id: '/api/public/sup/sync-catalog'
      path: '/api/public/sup/sync-catalog'
      fullPath: '/api/public/sup/sync-catalog'
      preLoaderRoute: typeof ApiPublicSupSyncCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sup/shipping': {
      id: '/api/public/sup/shipping'
      path: '/api/public/sup/shipping'
      fullPath: '/api/public/sup/shipping'
      preLoaderRoute: typeof ApiPublicSupShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/audit/connections': {
      id: '/api/public/audit/connections'
      path: '/api/public/audit/connections'
      fullPath: '/api/public/audit/connections'
      preLoaderRoute: typeof ApiPublicAuditConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  OrigenesRoute: OrigenesRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SeguimientoRoute: SeguimientoRoute,
  ShippingRoute: ShippingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  ProductosSkuRoute: ProductosSkuRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiPublicAuditConnectionsRoute: ApiPublicAuditConnectionsRoute,
  ApiPublicSupShippingRoute: ApiPublicSupShippingRoute,
  ApiPublicSupSyncCatalogRoute: ApiPublicSupSyncCatalogRoute,
  ApiPublicSupSyncTrackingRoute: ApiPublicSupSyncTrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
